# Meta/Facebook - Greenhouse
name: Meta
career_urls:
  - https://www.metacareers.com
ats_type: null
enabled: true
keyword_filters:
  - intern
  - internship
deny_filters:
  - Senior
  - Staff
  - Principal
